
--create _DWPromotion view as 
SELECT       d.RECID  AS PromotionAlternativeKey, d.DESCRIPTION, d.FROMDATE, d.TODATE, d.DELIVERYDATE, d.QUANTITY, d.DISCOUNT, d.PRICEDISCOUNT, ISNULL(l.NAME, N'الكل') AS Location, d.ITEMGROUP, d.DESCACTIVE, 
                         d.CREATEDATE, d.STATUS, d.SORTDISC, d.DATAAREAID AS CompanyName, ISNULL(CASE WHEN d .MODIFIEDDATETIME >= l.MODIFIEDDATETIME THEN d .MODIFIEDDATETIME ELSE l.MODIFIEDDATETIME END, 
                         d.MODIFIEDDATETIME) AS MODIFIEDDATETIME
FROM            dbo.DESCSHOW AS d LEFT OUTER JOIN
                      dbo.INVENTLOCATION AS l ON d.WAREHOUSE = l.INVENTLOCATIONID AND d.DATAAREAID = l.DATAAREAID




                      --5637156079   