ALTER VIEW [dbo].[_DWCar]
AS
SELECT        TRANSPORTCODE AS CarAlternativeKey, CARS AS CarNumber, DESCRIPTION AS CarName, 1 AS CarType, DESCRIPTION, DATAAREAID,dateadd(Hour,2, MODIFIEDDATETIME)as MODIFIEDDATETIME
FROM            dbo.INTRASTATTRANSPORTMODE
GO