
ALTER VIEW [dbo].[_DWCustomer]
AS
SELECT        c.ACCOUNTNUM AS CustomerAlternativeKey, c.NAME AS CustomerName, g.NAME AS CustomerGroup, c.IDNATIONALSTR, f.TXT AS CustomerClassification, dbo.birthdate(c.IDNATIONALSTR) AS birthdate, 
                         dbo.Gendr(c.IDNATIONALSTR) AS Gender, dbo.CustType(c.PARTYTYPE) AS CustomerType, c.DATAAREAID, dateadd(HOUR,2,ISNULL(CASE WHEN c.MODIFIEDDATETIME >= g.MODIFIEDDATETIME OR
                         c.MODIFIEDDATETIME >= f.MODIFIEDDATETIME THEN c.MODIFIEDDATETIME WHEN g.MODIFIEDDATETIME >= f.MODIFIEDDATETIME THEN g.MODIFIEDDATETIME ELSE f.MODIFIEDDATETIME END, c.MODIFIEDDATETIME) 
                         )AS MODIFIEDDATETIME
FROM            dbo.CUSTTABLE AS c LEFT OUTER JOIN
                         dbo.CUSTGROUP AS g ON c.CUSTGROUP = g.CUSTGROUP AND g.DATAAREAID = c.DATAAREAID LEFT OUTER JOIN
                         dbo.CUSTCLASSIFICATIONGROUP AS f ON c.CUSTCLASSIFICATIONID = f.CODE AND f.DATAAREAID = c.DATAAREAID